version: "2.3"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus-config/:/etc/prometheus
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - "GF_INSTALL_PLUGINS=grafana-piechart-panel"
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=password"
      - "GF_USERS_ALLOW_SIGN_UP=false"
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning
