global:
  # How frequently to scrape targets by default.
  # Default 15s
  scrape_interval: 60s
  # How frequently to evaluate rules.
  # Default 15s
  evaluation_interval: 15s
  # How long until a scrape request times out.
  # Default to 10s.
  # Required because cp-demo is using cpu throttling, so let's leave enough time to fetch the metrics in particular for the first time as it needs to compile all rexps
  scrape_timeout: 30s

scrape_configs:
  - job_name: Confluent Cloud
    scrape_interval: 1m
    scrape_timeout: 1m
    honor_timestamps: true
    static_configs:
      - targets:
        - api.telemetry.confluent.cloud
    scheme: https
    basic_auth:
      username: xxxxxxx
      password: xxxxxxx
    metrics_path: /v2/metrics/cloud/export
    params:
      "resource.kafka.id":
        - lkc-ropy7
